version: "3.8"
services:
  backend:
    build: .
    container_name: tic_tac_toe_backend
    ports:
      - "4000:4000"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: tictactoe_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1808
      POSTGRES_DB: TicTacToe
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
